### ISSUE TITLE
能把网易IM分离出来吗？

### ISSUE THREAD

**Issue by fuchenxi** [Soldoros/SSChat#6]

**Comment by Soldoros** [comment]
我有静态版的 加我钉钉13540033103------------------ 原始邮件 ------------------
发件人: "Sunshine"<notifications@github.com>
发送时间: 2019年7月26日(星期五) 下午5:17
收件人: "Soldoros/SSChat"<SSChat@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Soldoros/SSChat] 能把网易IM分离出来吗？ (#6)


 
&mdash;

**Comment by fuchenxi** [comment]
已加~

**Comment by Soldoros** [comment]
加我钉钉发你



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sunshine <notifications@github.com&gt;
发送时间: 2019年10月23日 10:17
收件人: Soldoros/SSChat <SSChat@noreply.github.com&gt;
抄送: soldoros <765970680@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[Soldoros/SSChat] 能把网易IM分离出来吗？ (#6)




Closed #6.
